const state = { crops: {}, markets: [], buyers: [], selectedCrop: null, path: 'shop', recognition: null };
const $ = (id) => document.getElementById(id);

async function loadData() {
  const response = await fetch('/api/bootstrap');
  if (!response.ok) throw new Error('Could not load market data');
  const data = await response.json();
  state.crops = data.crops; state.markets = data.markets; state.buyers = data.buyers;
  renderCrops(); renderGrades(data.quality_grades); renderMarkets(); renderBuyerFilter();
}
function renderCrops() { $('crop-grid').innerHTML = Object.entries(state.crops).map(([name, crop]) => `<button class="crop-card" data-crop="${name}"><span class="crop-icon">${crop.icon}</span><strong>${name}</strong><small>${crop.unit}</small></button>`).join(''); document.querySelectorAll('[data-crop]').forEach((button) => button.addEventListener('click', () => selectCrop(button.dataset.crop))); }
function renderGrades(grades) { $('grade').innerHTML = Object.entries(grades).map(([name, value]) => `<option value="${name}">${name}</option>`).join(''); }
function renderMarkets() { $('map-list').innerHTML = state.markets.map((market) => `<article class="market-card"><div><h3>${market.Market}</h3><p>${market.Location} · ${market.Distance} km away</p><p>Landmarks: ${market.Landmarks}</p></div><div class="card-actions"><a target="_blank" href="${mapsUrl(market.Location)}">View market</a><a target="_blank" href="${directionsUrl(market.Location)}">Directions</a></div></article>`).join(''); }
function renderBuyerFilter() { $('buyer-crop').innerHTML = Object.keys(state.crops).map((crop) => `<option>${crop}</option>`).join(''); $('buyer-crop').addEventListener('change', renderBuyers); renderBuyers(); }
function renderBuyers() { const crop = $('buyer-crop').value; $('buyer-list').innerHTML = state.buyers.filter((buyer) => buyer.Crop === crop).map((buyer) => `<article class="buyer-card"><div><strong>${buyer.Buyer}</strong><p>${buyer.Type} · ${buyer.Location}</p><p>Quantity: ${buyer.Quantity}</p></div><div class="offer-price">₹${buyer.Price}<small>/kg</small></div><button class="primary-button" onclick="connectBuyer('${buyer.Buyer}')">Connect</button></article>`).join(''); }
function selectCrop(crop) { state.selectedCrop = crop; document.querySelectorAll('.crop-card').forEach((button) => button.classList.toggle('selected', button.dataset.crop === crop)); $('results').classList.remove('hidden'); updateRecommendation(); $('results').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
async function updateRecommendation() { if (!state.selectedCrop) return; const payload = { crop: state.selectedCrop, location: $('location').value, quantity: Number($('quantity').value), transport_cost: Number($('transport').value), grade: $('grade').value, days: 3 }; const response = await fetch('/api/recommendation', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(payload) }); const result = await response.json(); $('metrics').innerHTML = `<div class="metric"><small>Fair price for grade</small><strong>₹${result.best.price.toFixed(2)}/kg</strong></div><div class="metric"><small>Best nearby market</small><strong>${result.best.location}</strong></div><div class="metric"><small>Your distance</small><strong>${result.best.distance} km</strong></div>`; $('recommendation').innerHTML = `<strong>Fair-price recommendation:</strong> ${result.recommendation} could leave about <strong>₹${result.recommendation_value.toLocaleString('en-IN')} net</strong> for ${payload.quantity.toLocaleString('en-IN')} kg after estimated costs.`; renderDetail(result); }
function renderDetail(result) { $('detail-panel').innerHTML = state.path === 'shop' ? `<div class="detail-card"><div class="detail-row"><div><h3>${result.best.market}</h3><p>${result.rental.shop} · ${result.rental.landmark}</p><p>₹${result.best.price.toFixed(2)}/kg for ${$('grade').value.toLowerCase()}</p></div><div><p>Daily rent: ₹${result.rental.daily_rent.toLocaleString('en-IN')}</p><p>Refundable deposit: ₹${result.rental.security_deposit.toLocaleString('en-IN')}</p><strong>Estimated net: ₹${result.shop_net.toLocaleString('en-IN')}</strong></div><a class="primary-button" target="_blank" href="${directionsUrl(result.best.location)}">Open route</a></div></div>` : `<div class="buyer-list">${result.offers.map((offer) => `<article class="buyer-card"><div><strong>${offer.buyer}</strong><p>${offer.type} · ${offer.location}</p></div><div class="offer-price">₹${offer.price}/kg<p>Net: ₹${offer.net_earning.toLocaleString('en-IN')}</p></div><button class="primary-button" onclick="connectBuyer('${offer.buyer}')">Connect</button></article>`).join('')}</div>`; }
function mapsUrl(location) { return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location + ' market')}`; }
function directionsUrl(location) { const origin = $('location')?.value ? `&origin=${encodeURIComponent($('location').value)}` : ''; return `https://www.google.com/maps/dir/?api=1${origin}&destination=${encodeURIComponent(location + ' market')}`; }
function connectBuyer(name) { $('voice-status').textContent = `Connection request sent to ${name}.`; }
function switchView(view) { document.querySelectorAll('.view').forEach((item) => item.classList.remove('active-view')); $(`${view}-view`).classList.add('active-view'); document.querySelectorAll('.nav-link').forEach((link) => link.classList.toggle('active', link.dataset.view === view)); }
function setupVoice() { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { $('voice-button').textContent = 'Voice input unavailable'; return; } state.recognition = new SpeechRecognition(); state.recognition.lang = 'en-IN'; state.recognition.onstart = () => { $('voice-button').textContent = 'Listening...'; }; state.recognition.onresult = (event) => { const text = event.results[0][0].transcript; $('voice-status').textContent = `Heard: ${text}`; const match = Object.keys(state.crops).find((crop) => text.toLowerCase().includes(crop.toLowerCase()) || (crop === 'Chilli' && /mirchi|chili/.test(text.toLowerCase()))); if (match) selectCrop(match); }; state.recognition.onend = () => { $('voice-button').textContent = '🎙 Start voice input'; }; $('voice-button').addEventListener('click', () => state.recognition.start()); }

document.querySelectorAll('.nav-link').forEach((link) => link.addEventListener('click', () => switchView(link.dataset.view))); $('menu-button').addEventListener('click', () => document.querySelector('.sidebar').classList.toggle('open')); $('grade').addEventListener('change', updateRecommendation); ['location', 'quantity', 'transport'].forEach((id) => $(id).addEventListener('change', updateRecommendation)); document.querySelectorAll('.path-button').forEach((button) => button.addEventListener('click', () => { state.path = button.dataset.path; document.querySelectorAll('.path-button').forEach((item) => item.classList.toggle('active', item === button)); updateRecommendation(); })); setupVoice(); loadData().catch((error) => { $('voice-status').textContent = error.message; });
